import type { Metadata } from 'next';
import Link from 'next/link';
import MarkdownToPdf from '@/components/tools/MarkdownToPdf';

export const metadata: Metadata = {
  title: 'Markdown to PDF Converter — Free, No Signup',
  description:
    'Convert markdown to PDF in your browser: paste or open a .md file, preview with syntax highlighting and tables, download as PDF with selectable text. Free and private.',
};

export default function MarkdownToPdfPage() {
  return (
    <div className="mx-auto w-full max-w-6xl px-4 py-12 md:py-16">
      <div className="no-print mb-8 max-w-3xl">
        <h1 className="text-3xl font-semibold tracking-tight text-gray-950 md:text-4xl">
          Markdown to PDF converter
        </h1>
        <p className="mt-4 text-base text-gray-600">
          Paste markdown or open a <code className="rounded bg-gray-100 px-1.5 py-0.5 text-sm">.md</code>{' '}
          file, check the preview, and download a PDF. Everything runs in your browser — your
          document is never uploaded.
        </p>
      </div>

      <MarkdownToPdf />

      <div className="no-print mx-auto mt-16 max-w-3xl space-y-10 text-gray-700">
        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-gray-950">What the PDF preserves</h2>
          <ul className="list-disc space-y-2 pl-6">
            <li><strong>Headings and document structure</strong> — with sensible page-break behavior (no heading orphaned at the bottom of a page).</li>
            <li><strong>Code blocks with syntax highlighting</strong> — kept together across page breaks where possible.</li>
            <li><strong>Tables</strong> — rendered as real tables, not ASCII art.</li>
            <li><strong>GitHub Flavored Markdown</strong> — task lists, strikethrough, and autolinks all render.</li>
            <li><strong>Selectable, searchable text</strong> — the PDF is generated by your browser&apos;s print engine, not rasterized to images, so copy-paste and Ctrl+F work in the output.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-gray-950">Why the print dialog?</h2>
          <p>
            Browser print engines are the highest-quality HTML-to-PDF renderers that exist — better
            than any JavaScript PDF library. Tools that generate PDFs directly in JavaScript either
            rasterize the page into blurry images or lose most CSS. Routing through{' '}
            <em>Save as PDF</em> costs one extra click and produces a document with real vector
            text, working links, and correct pagination.
          </p>
          <p>
            Tip: in the print dialog, set margins to <em>Default</em> and disable{' '}
            <em>Headers and footers</em> for the cleanest output.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-gray-950">FAQ</h2>
          <div className="space-y-4">
            <div>
              <h3 className="font-semibold text-gray-900">Is my document uploaded anywhere?</h3>
              <p>No. Conversion happens entirely client-side. The markdown never leaves your machine.</p>
            </div>
            <div>
              <h3 className="font-semibold text-gray-900">Can I convert from the command line or CI?</h3>
              <p>
                For automation, pair a headless browser with this page, or share the markdown via
                our{' '}
                <Link href="/api-docs" className="text-indigo-700 underline">
                  API
                </Link>{' '}
                and let recipients export from the share page — every shared document has the same
                Export PDF button.
              </p>
            </div>
            <div>
              <h3 className="font-semibold text-gray-900">Do mermaid diagrams work?</h3>
              <p>
                Yes — <code className="rounded bg-gray-100 px-1.5 py-0.5 text-sm">```mermaid</code>{' '}
                code fences render as diagrams in the preview and print as vector graphics in the
                PDF.
              </p>
            </div>
            <div>
              <h3 className="font-semibold text-gray-900">What if I want a link instead of a file?</h3>
              <p>
                PDFs are for email attachments and archives; for everything else a link is lighter.{' '}
                <Link href="/" className="text-indigo-700 underline">
                  Share your markdown
                </Link>{' '}
                and send a URL that always shows the latest version — with the same PDF export
                available to every viewer.
              </p>
            </div>
          </div>
        </section>

        <section className="space-y-3 rounded-2xl bg-indigo-50 p-6">
          <h2 className="text-xl font-semibold text-gray-950">More markdown tools</h2>
          <p>
            <Link href="/markdown-table-generator" className="text-indigo-700 underline">Markdown table generator</Link>{' · '}
            <Link href="/markdown-to-html" className="text-indigo-700 underline">Markdown to HTML</Link>{' · '}
            <Link href="/readme-generator" className="text-indigo-700 underline">README generator</Link>{' · '}
            <Link href="/markdown-cheat-sheet" className="text-indigo-700 underline">Markdown cheat sheet</Link>{' · '}
            <Link href="/" className="text-indigo-700 underline">Share markdown as a link</Link>
          </p>
        </section>
      </div>
    </div>
  );
}
